name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Code to EC2 via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          remote-user: ubuntu
          server-ip: ${{ secrets.SERVER_IP }}
          remote-path: /home/ubuntu/github-ci-cd-node-app

      - name: Run Build Commands on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/github-ci-cd-node-app
            npm ci
            npm test
            npm run build


