name: Security Audit

on:
  schedule:
    - cron: '0 3 * * 1'   # Every Monday 3 AM UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm ci

    - name: Run npm audit
      run: npm audit --audit-level=moderate
